import type { Metadata } from "next";
import { Montserrat, Geist_Mono } from "next/font/google";
import { Navbar } from "@/components/site/navbar";
import { CookieBanner } from "@/components/site/CookieBanner";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        {children}
        <CookieBanner />
      </body>
    </html>
  );
}
